config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  
  root to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/agreement', to: 'static_pages#agreement'
  get '/image/:id', to: 'images#show'
  
  resources :users do
     member do
      get :following, :followers
    end
  end
  resources :images,        only: [:index, :new, :show, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :likes,         only: [:create, :destroy]
end

app/views/layouts/_footer.html.slim
footer.footer
  nav.navbar
    ul.nav.navbar-nav.navbar-right
      - if user_signed_in?
        li = link_to "写真アップロード", new_image_path
        li = link_to "About", about_path
      - else
        li = link_to "About", about_path

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .container
    .navbar-header
      button.navbar-toggle type="button" data-toggle="collapse" data-target="#gnavi"
        span.sr-only メニュー
        span.icon-bar
        span.icon-bar
        span.icon-bar
      - if user_signed_in?
        = link_to "instagram clone", images_path, id: "logo"
      - else
        = link_to "instagram clone", root_path, id: "logo"
    nav#gnavi.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li = link_to 'マイページ', user_path(current_user)
          li = link_to '編集', edit_user_registration_path
          li = link_to 'ログアウト', destroy_user_session_path, method: :delete
        - else
          li = link_to "Home", root_path
          li = link_to "Help", help_path
          li = link_to "ログイン", new_user_session_path

app/views/layouts/_rails_default.html.slim
= csrf_meta_tags
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/_shim.html.slim
/[if lt IE9]
  script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js" 

app/views/layouts/application.html.slim
doctype html
html
  head
    title = full_title(yield(:title))
    == render 'layouts/rails_default'
    == render 'layouts/shim'
  body
    == render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")
      == yield
      == render 'layouts/footer'